CREATE TABLE IF NOT EXISTS HIKES (
	"IDHike"	INTEGER NOT NULL UNIQUE,
	"Length"	NUMERIC NOT NULL,
	"ExpectedTime"	NUMERIC NOT NULL,
	"Ascent"	NUMERIC NOT NULL,
	"Difficulty"	TEXT NOT NULL,
	"StartPoint"	TEXT NOT NULL,
	"EndPoint"	TEXT NOT NULL,
	"ReferencePoints"	TEXT,
	"Description"	TEXT,
	PRIMARY KEY("IDHike")
);

CREATE TABLE IF NOT EXISTS "POINTS" (
	"IDPoint"	INTEGER NOT NULL,
	"Name"	TEXT NOT NULL,
	"Coordinates"	TEXT NOT NULL,
	"GeographicalArea"	TEXT NOT NULL,
	"TypeOfPoint"	TEXT NOT NULL,
	PRIMARY KEY("IDPoint" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS HUTS (
	"IDPoint"	INTEGER NOT NULL,
    FOREIGN KEY("IDPoint") REFERENCES "POINTS"("IDPoint")
);

CREATE TABLE IF NOT EXISTS "PARKINGS" (
	"IDPoint"	INTEGER NOT NULL,
    FOREIGN KEY("IDPoint") REFERENCES "POINTS"("IDPoint")
);

CREATE TABLE IF NOT EXISTS "USERS" (
	Username VARCHAR NOT NULL PRIMARY KEY,
	Type VARCHAR NOT NULL,
	Password VARCHAR NOT NULL,
	Salt VARCHAR NOT NULL,
	First_Name VARCHAR,
	Last_Name VARCHAR,
	Phone_Number VARCHAR
);

CREATE TABLE IF NOT EXISTS "TOKENS" (
	Email VARCHAR NOT NULL PRIMARY KEY,
	Token VARCHAR NOT NULL
);